<a href="https://colab.research.google.com/github/adityab-tech/DC/blob/main/DC1_adi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#KNN Classifier

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import kagglehub
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report

In [2]:
df=pd.read_csv('/content/KNNAlgorithmDataset.csv')

In [3]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [4]:
df.describe()

,id,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
count,5.690000e+02,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,0.0
mean,3.037183e+07,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,...,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946,NaN
std,1.250206e+08,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,...,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061,NaN
min,8.670000e+03,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,...,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040,NaN
25%,8.692180e+05,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,...,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460,NaN
50%,9.060240e+05,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,...,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040,NaN
75%,8.813129e+06,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,...,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080,NaN
max,9.113205e+08,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,...,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
 32  Unnamed: 32              0 non-null      float64
dtypes: float64(31), int64(1), object(1)
memory usage: 146.8+ KB

In [6]:
df.shape

(569, 33)

In [7]:
df.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64

In [8]:
df['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [9]:
df.drop(columns='Unnamed: 32',inplace=True)

In [10]:
X = df.drop('diagnosis', axis=1)
y = df['diagnosis'].map({'M': 1, 'B': 0})

In [11]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [12]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [13]:
def euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1 - x2) ** 2))

In [14]:
def knn_predict(X_train, y_train, X_test, k=5):
    predictions = []
    for test_point in X_test:
        # Calculate distance from every training point
        distances = []
        for i in range(len(X_train)):
            distance = euclidean_distance(test_point,X_train[i])
            distances.append((distance, y_train.iloc[i]))

        distances.sort(key=lambda x: x[0])                         # sort by dist
        nearest = distances[:k]                                    # get knn
        labels = [label for distance, label in nearest]            # get labels
        prediction = max(set(labels), key=labels.count)            # majority voting
        predictions.append(prediction)
    return np.array(predictions)

In [15]:
k = 5
y_pred = knn_predict(X_train,y_train,X_test,k)

In [16]:
print("K =", k)
print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

K = 5
Accuracy: 0.956140350877193

Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.99      0.97        72
           1       0.97      0.90      0.94        42

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114

#Minimum Distance Classifier

In [17]:
# centroid of class 0 (benign and maligant)
centroid_0 = X_train[y_train.values == 0].mean(axis=0)
centroid_1 = X_train[y_train.values == 1].mean(axis=0)

In [18]:
def minimum_distance_classifier(X_test, centroid_0, centroid_1):
    predictions = []
    for x in X_test:
        # dist from class 0 and 1 centroid
        distance_0 = np.sqrt(np.sum((x - centroid_0) ** 2))
        distance_1 = np.sqrt(np.sum((x - centroid_1) ** 2))
        # nearest centriod
        if distance_0 < distance_1:
            predictions.append(0)
        else:
            predictions.append(1)
    return np.array(predictions)

In [19]:
y_pred = minimum_distance_classifier(X_test,centroid_0,centroid_1)

In [20]:
print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.9210526315789473

Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.99      0.94        72
           1       0.97      0.81      0.88        42

    accuracy                           0.92       114
   macro avg       0.94      0.90      0.91       114
weighted avg       0.93      0.92      0.92       114

#Linear Regression

In [21]:
!pip install ucimlrepo
from ucimlrepo import fetch_ucirepo
concrete = fetch_ucirepo(id=165)

X = concrete.data.features
y = concrete.data.targets

Collecting ucimlrepo
  Downloading ucimlrepo-0.0.7-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from ucimlrepo) (2.2.3)
Requirement already satisfied: certifi>=2020.12.5 in /usr/local/lib/python3.13/dist-packages (from ucimlrepo) (2026.7.22)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.0.0->ucimlrepo) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
Downloading ucimlrepo-0.0.7-py3-none-any.whl (8.0 kB)
Installing collected packages: ucimlrepo
Successfully installed ucimlrepo-0.0.7

In [22]:
print(X.head())
print(y.head())

   Cement  Blast Furnace Slag  Fly Ash  Water  Superplasticizer  \
0   540.0                 0.0      0.0  162.0               2.5
1   540.0                 0.0      0.0  162.0               2.5
2   332.5               142.5      0.0  228.0               0.0
3   332.5               142.5      0.0  228.0               0.0
4   198.6               132.4      0.0  192.0               0.0

   Coarse Aggregate  Fine Aggregate  Age
0            1040.0           676.0   28
1            1055.0           676.0   28
2             932.0           594.0  270
3             932.0           594.0  365
4             978.4           825.5  360
   Concrete compressive strength
0                          79.99
1                          61.89
2                          40.27
3                          41.05
4                          44.30

In [23]:
from sklearn.metrics import mean_squared_error, r2_score

In [24]:
data = pd.concat([X, y], axis=1)
data = data.dropna()

X = data.iloc[:, :-1]
y = data.iloc[:, -1]

In [25]:
# Convert to numpy
X = np.asarray(X)
y = np.asarray(y).ravel()

print("X shape:", X.shape)
print("y shape:", y.shape)
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

X shape: (1030, 8)
y shape: (1030,)

In [26]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [27]:
print(X_train.shape)
print(X_test.shape)

(824, 8)
(206, 8)

In [28]:
class LinearRegressionScratch:

    def __init__(self, learning_rate=0.01, epochs=1000):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.weights = None

    def fit(self, X, y):

        # Add column of 1s for bias
        X = np.c_[np.ones(X.shape[0]), X]
        self.weights = np.zeros(X.shape[1])
        for i in range(self.epochs):                            #grad descent
            y_pred = X @ self.weights
            error = y_pred - y
            gradient = (2 / X.shape[0]) * (X.T @ error)
            self.weights -= self.learning_rate * gradient

    def predict(self, X):
        # Add column of 1s
        X = np.c_[np.ones(X.shape[0]), X]
        # Prediction
        return X @ self.weights

In [29]:
def evaluate_model(y_test, y_pred):

    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, y_pred)

    print("MSE:", mse)
    print("RMSE:", rmse)
    print("R² Score:", r2)
    print("R² Percentage:", r2 * 100, "%")

In [30]:
model = LinearRegressionScratch()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
evaluate_model(y_test, y_pred)

MSE: 96.719977364821
RMSE: 9.834631531726087
R² Score: 0.6246462935537254
R² Percentage: 62.46462935537254 %

#Logistic Regression

In [32]:
df2=pd.read_csv('/content/news_dataset.csv',engine='python',on_bad_lines='skip')

In [33]:
print(df2.head())
print(df2.columns)
print(df2.shape)

                                               title  \
0   WATCH: Trump Just Told All The Anti-Gay Bigot...
1  China backs U.N. call for justice in Yemen, U....
2  THE PEOPLE’S PRESIDENT: Trump Meets With Coal ...
3  WSJ REPORTER RIPS INTO DEM CANDIDATES For Thei...
4  Lawmakers aim to delay U.S. ceding control of ...

                                                text       subject  \
0  A whole lot of evangelical Trump voters just d...          News
1  GENEVA (Reuters) - China signaled on Wednesday...     worldnews
2                                                         politics
3  THE WSJ S MARY KISSEL NAILS IT ON THE DEM DEBA...      politics
4  WASHINGTON (Reuters) - Critics of a plan for t...  politicsNews

                  date  label
0    November 13, 2016      0
1  September 13, 2017       1
2         Feb 16, 2017      0
3         Nov 15, 2015      0
4  September 13, 2016       1
Index(['title', 'text', 'subject', 'date', 'label'], dtype='object')
(6000, 5)

In [34]:
df2['content'] = df2['title'].fillna('') + ' ' + df2['text'].fillna('')
X = df2['content']
y = df2['label']

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words='english',ngram_range=(1, 2),max_features=20000,sublinear_tf=True,min_df=2,max_df=0.95)
X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

In [37]:
class LogisticRegressionScratch:

    def __init__(self, learning_rate=0.1, epochs=1000, reg_lambda=0.01):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.reg_lambda = reg_lambda
        self.weights = None
        self.bias = 0

    # Sigmoid function
    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    # Training
    def fit(self, X, y):
      X = X.toarray()
      n_samples, n_features = X.shape
      self.weights = np.zeros(n_features)
      self.bias = 0
      for epoch in range(self.epochs):
        z = X @ self.weights + self.bias
        y_pred = self.sigmoid(z)
        dw = (1 / n_samples) * (X.T @ (y_pred - y))
        dw += self.reg_lambda * self.weights
        db = (1 / n_samples) * np.sum(y_pred - y)
        self.weights -= self.learning_rate * dw
        self.bias -= self.learning_rate * db

    def predict(self, X):
        X = X.toarray()
        z = X @ self.weights + self.bias
        probabilities = self.sigmoid(z)
        return (probabilities >= 0.5).astype(int)

In [38]:
model = LogisticRegressionScratch(learning_rate=0.1,epochs=1000)
model.fit(X_train, y_train.values)
y_pred = model.predict(X_test)

In [39]:
from sklearn.metrics import confusion_matrix
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.9475

Confusion Matrix:
[[565  35]
 [ 28 572]]

Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.94      0.95       600
           1       0.94      0.95      0.95       600

    accuracy                           0.95      1200
   macro avg       0.95      0.95      0.95      1200
weighted avg       0.95      0.95      0.95      1200

#SVM

In [40]:
y_train_svm = np.where(y_train.values == 0, -1, 1)
y_test_svm = np.where(y_test.values == 0, -1, 1)

In [41]:
class SVMFromScratch:

    def __init__(self, learning_rate=0.001, epochs=1000, C=1.0):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.C = C
        self.weights = None
        self.bias = 0

    def fit(self, X, y):
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.bias = 0

        for epoch in range(self.epochs):
            scores = X @ self.weights + self.bias
            margins = y * scores
            mask = margins < 1
            dw = self.weights - self.C * (X.T @ (y * mask)) / n_samples
            db = -self.C * np.sum(y * mask) / n_samples
            self.weights -= self.learning_rate * dw
            self.bias -= self.learning_rate * db

    def predict(self, X):
        scores = X @ self.weights + self.bias
        return np.where(scores >= 0, 1, -1)

In [42]:
model = SVMFromScratch(learning_rate=0.001,epochs=1000,C=1.0)
model.fit(X_train, y_train_svm)
y_pred_svm = model.predict(X_test)
y_pred = np.where(y_pred_svm == -1, 0, 1)

In [43]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.9491666666666667

Confusion Matrix:
[[556  44]
 [ 17 583]]

Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.93      0.95       600
           1       0.93      0.97      0.95       600

    accuracy                           0.95      1200
   macro avg       0.95      0.95      0.95      1200
weighted avg       0.95      0.95      0.95      1200

In [44]:
for C in [0.001, 0.01, 0.1, 1, 10]:

    model = SVMFromScratch(
        learning_rate=0.001,
        epochs=1000,
        C=C
    )

    model.fit(X_train, y_train_svm)

    pred = model.predict(X_test)
    pred = np.where(pred == -1, 0, 1)

    print(
        "C:", C,
        "Accuracy:", accuracy_score(y_test, pred),
        "Weight norm:", np.linalg.norm(model.weights),
        "Bias:", model.bias
    )

C: 0.001 Accuracy: 0.9491666666666667 Weight norm: 4.4100024272831684e-05 Bias: 0.0
C: 0.01 Accuracy: 0.9491666666666667 Weight norm: 0.00044100024272831687 Bias: 0.0
C: 0.1 Accuracy: 0.9491666666666667 Weight norm: 0.004410002427283169 Bias: 0.0
C: 1 Accuracy: 0.9491666666666667 Weight norm: 0.04410002427283168 Bias: 0.0
C: 10 Accuracy: 0.9491666666666667 Weight norm: 0.44100024272831695 Bias: 0.0

#K-Means

In [46]:
from sklearn.datasets import load_wine
wine = load_wine(as_frame=True)
df = wine.frame

print(df.head())
print(df.shape)

   alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80
1    13.20        1.78  2.14               11.2      100.0           2.65
2    13.16        2.36  2.67               18.6      101.0           2.80
3    14.37        1.95  2.50               16.8      113.0           3.85
4    13.24        2.59  2.87               21.0      118.0           2.80

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04
1        2.76                  0.26             1.28             4.38  1.05
2        3.24                  0.30             2.81             5.68  1.03
3        3.49                  0.24             2.18             7.80  0.86
4        2.69                  0.39             1.82             4.32  1.04

   od280/od315_of_diluted_wines  proline  target
0                          3.92   1065.0       0
1                          3.40   1050.0       0
2                          3.17   1185.0       0
3                          3.45   1480.0       0
4                          2.93    735.0       0
(178, 14)